### ISSUE TITLE
can you add a demo to show how to use this napari-3d-ortho-viewer

### ISSUE THREAD

**Issue by chaoshunh** [gatoniel/napari-3d-ortho-viewer#2]
I have spent a long time and still didn't figure it out how to call this plugin. Btw when I tryied to use napari_plugin_manager.register(napari_3d_ortho_viewer, name="3D Ortho viewer") and it says napari_plugin_manager doesn't contain register function. It is very confusing.

**Comment by gatoniel** [comment]
hi there,
does this help?

https://github.com/gatoniel/napari-3d-ortho-viewer/assets/40384506/4296dc11-ea37-40a0-8b17-eeb77480672f

Also, maybe you need to download a newer version of the plugin for newer napari versions. It will come soon.

**Comment by gatoniel** [comment]
Please install version 0.1.5 in case you have troubles reproducing the above video.

**Comment by gatoniel** [comment]
There was no further user request / input.
